# Accelerate configuration for 4-GPU FSDP launches.
compute_environment: LOCAL_MACHINE
distributed_type: FSDP
num_processes: 4
machine_rank: 0
same_network: true
gpu_ids: all
mixed_precision: bf16
logger: none

fsdp_config:
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_forward_prefetch: false
  fsdp_min_num_params: 1000000
  fsdp_offload_params: true
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_sync_module_states: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASE
  limit_all_gathers: true

use_cpu: false
tpu_name: null
tpu_zone: null
deepspeed_config: {}

